# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "The Gersch Effect"
email: gersch@thegerscheffect.com
description: > # this means to ignore newlines until "baseurl:"
  This project is a proactive approach to teaching myself how build a blog. My goal for the next year is to transfrom this into a great interactive portfolio with functional tools for non-profits and local government work. I am a student at Miami Dade College transferring to Florida International University's School of Computer Science.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thegerscheffect.com" # the base hostname & protocol for your site
twitter_username: thegerscheffect
github_username:  thegerscheffect
linkedin_username: gersch

# Build settings
markdown: kramdown

# Disqus comment settings
enable_disqus: true
